### ISSUE TITLE
Wrong Convert at Float coordinates

### ISSUE THREAD

**Issue by akinba** [pauldzy/DZ_JSON#3]
It is usefull function for me but there are two problem to convert geojson

- Float coordinates convert with wrong sparator.
My encoding=Cp1254

SELECT
dz_json_main.sdo2geojson(
   p_input  => MDSYS.SDO_GEOMETRY(
       2003
      ,4326
      ,NULL
      ,MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1)
      ,MDSYS.SDO_ORDINATE_ARRAY(5.1,1.1, 8.2,1.2, 8.3,6.3, 5.4,7.4, 5.1,1.1)
  ) 
)  
FROM  
dual;

`Result >> {"type":"Polygon","coordinates":[[[5,1,1,1],[8,2,1,2],[8,3,6,3],[5,4,7,4],[5,1,1,1]]]}`
`Must Be>> {"type":"Polygon","coordinates":[[[5.1,1.1],[8.2,1.2],[8.3,6.3],[5.4,7.4],[5.1,1.1]]]}`

- And my layers use EPSG:2320, function transform projection EPSG:4326

SELECT
dz_json_main.sdo2geojson(
   p_input  => MDSYS.SDO_GEOMETRY(
       2003
      ,**2320**
      ,NULL
      ,MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1)
      ,MDSYS.SDO_ORDINATE_ARRAY(5.1,1.1, 8.2,1.2, 8.3,6.3, 5.4,7.4, 5.1,1.1)
  ) 
)  
FROM  
dual;
`{"type":"Polygon","coordinates":[[[25,5128124307869,-,00110333750003992],[25,5128401920781,-,00110243593888196],[25,5128410876016,-,00105645633891745],[25,5128151173605,-,00104653917268595],[25,5128124307869,-,00110333750003992]]]}`

i didnt want to transform 2320 to 4326.

**Comment by pauldzy** [comment]
Hi Akinba,

Thanks for your interest.  I see you are coming from a culture that uses the "," as a decimal indicator.  So the number is then being written as such (I actually did not know Turks used the comma that way) due to your localization setting.  I need to overrule that in the TO_CHAR I think to force the use of the "." instead.  Let me see about setting up a test environment to sort this out.  What are your exact NLS settings?

Secondly, I recently rewrote this package to follow the published GeoJSON standard here:
https://tools.ietf.org/html/rfc7946
In the new standard from August 2016, only WGS84 is allowed for GeoJSON.  This differs from the old unofficial standard that allowed a CRS object and any projection you wanted.  Now GeoJSON is similar to KML in that its only ever WGS84.  I still have the old code with the CRS object in this release
https://github.com/pauldzy/DZ_JSON/releases/tag/1.0
But moving forward I was not going to support these deprecated items.

Cheers,
Paul

**Comment by akinba** [comment]
Hi Paul,



SELECT * FROM nls_session_parameters;

NLS_LANGUAGE	TURKISH
NLS_TERRITORY	TURKEY
NLS_CURRENCY	TL
NLS_ISO_CURRENCY	TURKEY
NLS_NUMERIC_CHARACTERS	,.
NLS_CALENDAR	GREGORIAN
NLS_DATE_FORMAT	DD/MM/RRRR
NLS_DATE_LANGUAGE	TURKISH
NLS_SORT	TURKISH
NLS_TIME_FORMAT	HH24:MI:SSXFF
NLS_TIMESTAMP_FORMAT	DD/MM/RRRR HH24:MI:SSXFF
NLS_TIME_TZ_FORMAT	HH24:MI:SSXFF TZR
NLS_TIMESTAMP_TZ_FORMAT	DD/MM/RRRR HH24:MI:SSXFF TZR
NLS_DUAL_CURRENCY	TL
NLS_COMP	BINARY
NLS_LENGTH_SEMANTICS	BYTE
NLS_NCHAR_CONV_EXCP	FALSE


SELECT * FROM nls_database_parameters;

NLS_RDBMS_VERSION	12.1.0.2.0
NLS_NCHAR_CONV_EXCP	FALSE
NLS_LENGTH_SEMANTICS	BYTE
NLS_COMP	BINARY
NLS_DUAL_CURRENCY	$
NLS_TIMESTAMP_TZ_FORMAT	DD-MON-RR HH.MI.SSXFF AM TZR
NLS_TIME_TZ_FORMAT	HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_FORMAT	DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_FORMAT	HH.MI.SSXFF AM
NLS_SORT	BINARY
NLS_DATE_LANGUAGE	AMERICAN
NLS_DATE_FORMAT	DD-MON-RR
NLS_CALENDAR	GREGORIAN
NLS_NUMERIC_CHARACTERS	.,
NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_CHARACTERSET	TR8MSWIN1254
NLS_ISO_CURRENCY	AMERICA
NLS_CURRENCY	$
NLS_TERRITORY	AMERICA
NLS_LANGUAGE	AMERICAN

**Comment by akinba** [comment]
Hi Paul ,
thx for information about stanadartation for  geojson (http://geojson.org/) .
i know only spelling rules.

i will wait decimal issue for TURKISH

Thx a lot.

**Comment by akinba** [comment]
Hi Paul ,
i found a solution like this

`alter session set NLS_NUMERIC_CHARACTERS = '.,';`

from [here](http://stackoverflow.com/questions/24571355/nls-numeric-characters-setting-for-decimal)

**Comment by pauldzy** [comment]
Hi Akinba,
I haven't forgotten about you but has been busy week.  Just like you say I can set the NLS_NUMERIC_CHARACTERS flag individually on my TO_CHAR when I generate the ordinate.  However my uncertainty was about other JSON numbers and how they should be formatted.  I just have not read up on the matter. 

In my American localization I could have something like
{"type":"Polygon","usernumber":12.1234,"coordinates":[[[5.1,1.1],[8.2,1.2],[8.3,6.3],[5.4,7.4],[5.1,1.1]]]}

How would that 12.1234 be formatted in Turkish JSON?  Would you use the period or the comma?  Doesn't altering the session make all your JSON numbers be then American style?  

E.g. wouldn't you really want just the GeoJSON to have the American style and leave the other numbers as your default Turkish style?
{"type":"Polygon","usernumber":12,1234,"coordinates":[[[5.1,1.1],[8.2,1.2],[8.3,6.3],[5.4,7.4],[5.1,1.1]]]}

Paul

**Comment by pauldzy** [comment]
Ok Akinba,

I actually sat and read the docs.  So I take back my last comment.  There is no such thing as localized JSON numbers.  JSON by definition always uses a period as a decimal separator.  So if you wanted to provide a Turkish numeric value as JSON, then it would need to be a quoted string value.  So this makes it relatively easy to just add the NLS setting to my TO_CHAR for all number conversions.
TO_CHAR(p_input,'TM9','NLS_NUMERIC_CHARACTERS = ''.,''')
Note it took a bit to figure out that TM9 thing.  

So I think this should solve your issue.  

Cheers,
Paul
