### ISSUE TITLE
How do I create a FeatureCollection

### ISSUE THREAD

**Issue by mrisney** [pauldzy/DZ_JSON#5]
select crashid, dz_json_main.sdo2geojson(
   p_input  => sdo_aggr_set_union(CAST(COLLECT(geometry) AS mdsys.SDO_Geometry_Array),0.005)) as geom
from mv_test_crash_mv;

produces a {"type":"MultiPoint","coordinates":[[-104.183854791127,42.036294972676],[-104.198371439148,42.0216658714268],

doesn't produce a FeatureCollection, how would I write my query or aggregrate my geomteries and properties to do this ?

**Comment by pauldzy** [comment]
Hello Marc,

you can build features directly from a tabular query like this
```
SELECT  
dz_json_feature(  
    p_geometry => a.geometry 
   ,p_properties => dz_json_properties_vry(  
        dz_json_properties(  
            p_name => 'CrashID'  
           ,p_properties_number => a.crashid
        ) 
    )   
).toJSON(  
    p_2d_flag       => 'FALSE'  
   ,p_pretty_print  => 0  
   ,p_prune_number  => 8  
   ,p_add_bbox      => 'FALSE'  
)  AS features
FROM mv_test_crash_mv a;
```
or build the entire collection like this
```
SELECT
dz_json_feature_collection(
   features => CAST(MULTISET(
      SELECT
      dz_json_feature(  
          p_geometry => a.geometry 
         ,p_properties => dz_json_properties_vry(  
              dz_json_properties(  
                  p_name => 'CrashID'  
                 ,p_properties_number => a.crashid
              ) 
          )   
      )
      FROM mv_test_crash_mv a
  ) AS dz_json_feature_vry)
).toJSON(  
    p_2d_flag       => 'FALSE'  
   ,p_pretty_print  => 0  
   ,p_prune_number  => 8  
   ,p_add_bbox      => 'FALSE'  
) AS feature_collection
FROM dual;
```
For the latter option beware running out of memory if your query returns too many large records.

**Comment by pauldzy** [comment]
Hi Marc,
I added a better set of examples to the readme that expressly cover creation of feature collections.  I'll close the ticket assuming you are all set.

**Comment by mrisney** [comment]
Thanks for the examples. I have some SDO_GEOM queries that -  following your examples - I would like to use parallel query for performance gains. Is there any pattern that you could comment on that would  allow Parallel Execution ? If the output is appended into a temporary clob, I am not sure how this would be accomplished. Nonetheless, your examples are great. I am now interested in optimization hints. Thanks for this library BTW.
